
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jan 12 22:12:40 CET 2020
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 13;
  public static final int LT = 16;
  public static final int ELSE = 23;
  public static final int CP = 3;
  public static final int NOTEQ = 21;
  public static final int PLUS = 7;
  public static final int OR = 14;
  public static final int WHILE = 24;
  public static final int OP = 2;
  public static final int NOT = 15;
  public static final int IF = 22;
  public static final int GT = 17;
  public static final int CB = 5;
  public static final int DO = 25;
  public static final int OB = 4;
  public static final int NUMBER = 28;
  public static final int EOF = 0;
  public static final int DIV = 10;
  public static final int MINUS = 8;
  public static final int PRINT = 26;
  public static final int error = 1;
  public static final int EQ = 20;
  public static final int GTOREQ = 19;
  public static final int SC = 6;
  public static final int FOR = 29;
  public static final int LTOREQ = 18;
  public static final int MUL = 9;
  public static final int ASIG = 12;
  public static final int VAR = 27;
  public static final int UMINUS = 11;
}

